# Generated by Django 4.2.1 on 2023-07-02 07:25

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام شهر')),
            ],
        ),
        migrations.CreateModel(
            name='Classification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='دسته بندی')),
            ],
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.city', verbose_name='شهر انبار')),
            ],
        ),
        migrations.CreateModel(
            name='InventoryProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='مقدار به کیلوگرم')),
                ('inventory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.inventory', verbose_name='انبار')),
            ],
        ),
        migrations.CreateModel(
            name='JobOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(default='فروشنده ی خشکبار تهران', max_length=70)),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=30)),
                ('age', models.IntegerField()),
                ('Years_of_WorkExperience', models.IntegerField(default='2')),
                ('phone_number', models.CharField(blank=True, default='09192999154', max_length=11)),
                ('email', models.EmailField(max_length=50)),
                ('skills', models.CharField(default='توانایی مذاکره و روابط عمومی بالا', max_length=500)),
                ('previous_jobs', models.CharField(default='شغلی نداشته ام', max_length=400)),
                ('Parvane_Kasb', models.IntegerField(default='402349034')),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, verbose_name='نام تامین کننده')),
                ('email', models.EmailField(max_length=254, verbose_name='ایمیل')),
                ('phone_number', models.CharField(blank=True, default='+989123456789', max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+989123456789'. Up to 15 digits allowed.", regex='^\\+?98?\\d{9,15}$')], verbose_name='تلفن همراه')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, verbose_name=' نام محصول')),
                ('price', models.IntegerField(verbose_name=' قیمت هر کیلوگرم به تومان')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=6, verbose_name=' مقدار به کیلوگرم')),
                ('pic', models.ImageField(upload_to='', verbose_name='تصویر محصول')),
                ('grade', models.CharField(choices=[('a', 'درجه یک'), ('b', 'درجه دو')], default=('a', 'درجه یک'), max_length=20, verbose_name='کیفیت')),
                ('classification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.classification', verbose_name='دسته بندی')),
                ('supplier', models.ManyToManyField(to='company.supplier', verbose_name='تامین کننده')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='تعداد')),
                ('status', models.CharField(choices=[('ثبت شد', 'ثبت شد'), ('آماده ارسال', 'آماده ارسال')], default='ثبت شد', max_length=20, verbose_name='وضعیت')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.inventoryproduct', verbose_name='محصول')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='سفارش دهنده')),
            ],
        ),
        migrations.AddField(
            model_name='inventoryproduct',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.product', verbose_name=' نام محصول'),
        ),
    ]
